// The contents of our Tailwind theme are generated by Style Dictionary
const designTokens = require('@prism2/style-dictionary/build/js/tokens.cjs.js').default
// Destructure fontSize and color for additional transformation
const { color, font, size, ...otherTokens } = designTokens;
const { palette, ...rest } = color;
const { fontSize, lineHeight } = size;
module.exports = {
  ...otherTokens,
  colors: {
    ...palette,
    ...rest
  },
  ...font,
  ...size,
  ...otherTokens,
  fontSize: {
    xxs: [fontSize.xxs, { lineHeight: lineHeight.snug}],
    xs: [fontSize.xs, { lineHeight: lineHeight.snug }],
    sm: [fontSize.sm, { lineHeight: lineHeight.normal }],
    base: [fontSize.base, { lineHeight: lineHeight.normal }],
    lg: [fontSize.lg, { lineHeight: lineHeight.normal }],
    xl: [fontSize.xl, { lineHeight: lineHeight.normal }],
    '2xl': [fontSize['2xl'], { lineHeight: lineHeight.normal }],
    '3xl': [fontSize['xl'], { lineHeight: lineHeight.normal }],
    '4xl': [fontSize['4xl'], { lineHeight: lineHeight.snug }],
    '5xl': [fontSize['5xl'], { lineHeight: lineHeight.snug }],
    '6xl': [fontSize['6xl'], { lineHeight: lineHeight.snug }],
    '7xl': [fontSize['7xl'], { lineHeight: lineHeight.snug }],
    '8xl': [fontSize['8xl'], { lineHeight: lineHeight.tight }],
    '9xl': [fontSize['9xl'], { lineHeight: lineHeight.tight }],
  },
}
