export const priceTiers = ['$10,000', '$15,000', '$20,000', '$30,000', '$40,000', '$50,000', '$60,000', '$70,000', '$80,000', '$90,000', '$100,000'];
export const usStates = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New Y$or,000',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];
export const items = [
  'Daward Reynolds',
  'Darrn Towne',
  'Darin Apple',
  'Darin Cassler',
  'Darin Hazelnuts',
  'Benedict D Kessler',
  'Katelyn Rohan',
];
export const makes = [
  'Acura',
  'Alfa',
  'AMC',
  'Aston',
  'Audi',
  'Bentley',
  'BMW',
  'Bugatti',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Daewoo',
  'Datsun',
  'DeLorean',
  'Dodge',
  'Eagle',
  'Ferrari',
  'FIAT',
  'Fisker',
  'Ford',
  'Freightliner',
  'Genesis',
  'Geo',
  'GMC',
  'Honda',
  'HUMMER',
  'Hyundai',
  'INFINITI',
  'Isuzu',
  'Jaguar',
  'Jeep',
  'Karma',
  'Kia',
  'Lamborghini',
  'Land',
  'Lexus',
  'Lincoln',
  'Lotus',
  'Lucid',
  'Maserati',
  'Maybach',
  'MAZDA',
  'McLaren',
  'Mercedes',
  'Mercury',
  'MINI',
  'Mitsubishi',
  'Nissan',
  'Oldsmobile',
  'Plymouth',
  'Polestar',
  'Pontiac',
  'Porsche',
  'RAM',
  'Rivian',
  'Rolls',
  'Saab',
  'Saturn',
  'Scion',
  'SRT',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'Yugo',
];

export const users = [{ 'id':1, 'first_name':'Gael', 'last_name':'Dionsetti', 'email':'gdionsetti0@yellowpages.com', 'ip_address':'153.183.215.133' },
  { 'id':2, 'first_name':'Marybeth', 'last_name':'Maffey', 'email':'mmaffey1@thetimes.co.uk', 'ip_address':'116.182.87.55' },
  { 'id':3, 'first_name':'Gunter', 'last_name':'Cotta', 'email':'gcotta2@slideshare.net', 'ip_address':'155.151.154.1' },
  { 'id':4, 'first_name':'Pernell', 'last_name':'Sacks', 'email':'psacks3@oaic.gov.au', 'ip_address':'73.1.72.134' },
  { 'id':5, 'first_name':'Jude', 'last_name':'Olyet', 'email':'jolyet4@oaic.gov.au', 'ip_address':'8.119.44.44' },
  { 'id':6, 'first_name':'Aloise', 'last_name':'Roubottom', 'email':'aroubottom5@baidu.com', 'ip_address':'83.52.234.98' },
  { 'id':7, 'first_name':'Goddart', 'last_name':'Pike', 'email':'gpike6@bloomberg.com', 'ip_address':'157.175.175.252' },
  { 'id':8, 'first_name':'Marlyn', 'last_name':'Dinnis', 'email':'mdinnis7@mayoclinic.com', 'ip_address':'156.191.126.187' },
  { 'id':9, 'first_name':'Kelci', 'last_name':'Beddon', 'email':'kbeddon8@ehow.com', 'ip_address':'31.254.11.141' },
  { 'id':10, 'first_name':'Dall', 'last_name':'Showl', 'email':'dshowl9@redcross.org', 'ip_address':'60.102.18.244' },
  { 'id':11, 'first_name':'Mattheus', 'last_name':'Clubley', 'email':'mclubleya@cdc.gov', 'ip_address':'34.174.46.206' },
  { 'id':12, 'first_name':'Kris', 'last_name':'Wiggington', 'email':'kwiggingtonb@nature.com', 'ip_address':'11.124.183.252' },
  { 'id':13, 'first_name':'Berke', 'last_name':'Blowing', 'email':'bblowingc@ning.com', 'ip_address':'78.54.124.200' },
  { 'id':14, 'first_name':'Hill', 'last_name':'Cardozo', 'email':'hcardozod@livejournal.com', 'ip_address':'51.236.13.154' },
  { 'id':15, 'first_name':'Raynor', 'last_name':'Henrie', 'email':'rhenriee@noaa.gov', 'ip_address':'54.210.142.10' }];
