import React, { ReactElement } from 'react';
import * as P2 from '@prism2/icons-react';
import * as Solid from '@prism2/icons-react/24/solid';
import * as Mini from '@prism2/icons-react/20/solid';
import * as Outline from '@prism2/icons-react/24/outline';
import * as Interstate from '@prism2/icons-react/interstate';


let boxClass = 'grid grid-cols-[50px,1fr] text-left items-center text-xxs gap-2 w-[200px]';

interface IconProps extends React.ComponentProps<'svg'> {}

const IconSample = (
  { Icon, textColor = 'text-gray-400', iconClass = 'h-6', name = '' }:
  {Icon: React.FC<IconProps>, name: string, iconClass: string, textColor: string }
) => (
    <div className={boxClass}>
      <Icon className={iconClass} />
      <div className={textColor}>{name}</div>
    </div>
)

const interstateList = [
    [Interstate.AlarmAddSolidIcon, 'AlarmAddSolidIcon'],
    [ Interstate.AlarmClockSolidIcon,  'AlarmClockSolidIcon'],
    [ Interstate.AlarmSetSolidIcon,  'AlarmSetIcon'],
    [ Interstate.ArrowDownTrayIcon,  'ArrowDownTrayIcon'],
    [ Interstate.ArrowPathIcon,  'ArrowPathIcon'],
    [ Interstate.ArrowRightOnRectangleIcon,  'ArrowRightOnRectangleIcon'],
    [ Interstate.ArrowSmallDownIcon,  'ArrowSmallDownIcon'],
    [ Interstate.ArrowSmallUpIcon,  'ArrowSmallUpIcon'],
    [ Interstate.ArrowTopRightOnSquareIcon,  'ArrowTopRightOnSquareIcon'],
    [ Interstate.ArrowUpOnSquareIcon,  'ArrowUpOnSquareIcon'],
    [ Interstate.ArrowUpTrayIcon,  'ArrowUpTrayIcon'],
    [ Interstate.ArrowUturnLeftIcon,  'ArrowUturnLeftIcon'],
    [ Interstate.ArrowUturnRightIcon,  'ArrowUturnRightIcon'],
    [ Interstate.ArrowsPointingInIcon,  'ArrowsPointingInIcon'],
    [ Interstate.ArrowsPointingOutIcon,  'ArrowsPointingOutIcon'],
    [ Interstate.ArrowsRightLeftIcon,  'ArrowsRightLeftIcon'],
    [ Interstate.ArrowsUpDownIcon,  'ArrowsUpDownIcon'],
    [ Interstate.BackToStartSolidIcon,  'BackToStartSolidIcon'],
    [ Interstate.BarCodeSolidIcon,  'BarCodeSolidIcon'],
    [ Interstate.Bars3Icon,  'Bars3Icon'],
    [ Interstate.BellIcon,  'BellIcon'],
    [ Interstate.BoltIcon,  'BoltIcon'],
    [ Interstate.CalendarIcon,  'CalendarIcon'],
    [ Interstate.CameraIcon,  'CameraIcon'],
    [ Interstate.CarSolidIcon,  'CarSolidIcon'],
    [ Interstate.CarSideIcon,  'CarSideIcon'],
    [ Interstate.ChartPieIcon,  'ChartPieIcon'],
    [ Interstate.ChatBubbleLeftIcon,  'ChatBubbleLeftIcon'],
    [ Interstate.ChatBubbleLeftRightIcon,  'ChatBubbleLeftRightIcon'],
    [ Interstate.CheckCircleIcon,  'CheckCircleIcon'],
    [ Interstate.CheckmarkSolidIcon,  'CheckmarkSolidIcon'],
    [ Interstate.ChevronDownIcon,  'ChevronDownIcon'],
    [ Interstate.ChevronLeftIcon,  'ChevronLeftIcon'],
    [ Interstate.ChevronRightIcon,  'ChevronRightIcon'],
    [ Interstate.ChevronUpDownIcon,  'ChevronUpDownIcon'],
    [ Interstate.ChevronUpIcon,  'ChevronUpIcon'],
    [ Interstate.ClipboardCheckIcon,  'ClipboardCheckIcon'],
    [ Interstate.ClipboardIcon,  'ClipboardIcon'],
    [ Interstate.ClockIcon,  'ClockIcon'],
    [ Interstate.CloudArrowUpIcon,  'CloudArrowUpIcon'],
    [ Interstate.Cog8ToothIcon,  'Cog8ToothIcon'],
    [ Interstate.ConditionReportSolidIcon,  'ConditionReportSolidIcon'],
    [ Interstate.CreditCardIcon,  'CreditCardIcon'],
    [ Interstate.CupIcon,  'CupIcon'],
    [ Interstate.CurrencyDollarIcon,  'CurrencyDollarIcon'],
    [ Interstate.DamagesSolidIcon,  'DamagesSolidIcon'],
    [ Interstate.DetailsIcon,  'DetailsIcon'],
    [ Interstate.DevicePhoneMobileIcon,  'DevicePhoneMobileIcon'],
    [ Interstate.DocumentDuplicateIcon,  'DocumentDuplicateIcon'],
    [ Interstate.DocumentIcon,  'DocumentIcon'],
    [ Interstate.DocumentTextIcon,  'DocumentTextIcon'],
    [ Interstate.EllipsisHorizontalIcon,  'EllipsisHorizontalIcon'],
    [ Interstate.EllipsisVerticalIcon,  'EllipsisVerticalIcon'],
    [ Interstate.EnterSolidIcon,  'EnterSolidIcon'],
    [ Interstate.EnvelopeIcon,  'EnvelopeIcon'],
    [ Interstate.ExclaimationCircleIcon,  'ExclaimationCircleIcon'],
    [ Interstate.ExclamationTriangleIcon,  'ExclamationTriangleIcon'],
    [ Interstate.EyeIcon,  'EyeIcon'],
    [ Interstate.EyeSlashIcon,  'EyeSlashIcon'],
    [ Interstate.FileExcelSolidIcon,  'FileExcelSolidIcon'],
    [ Interstate.FilePdfSolidIcon,  'FilePdfSolidIcon'],
    [ Interstate.FileSpreadsheetSolidIcon,  'FileSpreadsheetIcon'],
    [ Interstate.FlagIcon,  'FlagIcon'],
    [ Interstate.FloppyDiskSolidIcon,  'FloppyDiskSolidIcon'],
    [ Interstate.ForkSpoonIcon,  'ForkSpoonIcon'],
    [ Interstate.FuelSolidIcon,  'FuelSolidIcon'],
    [ Interstate.FunnelIcon,  'FunnelIcon'],
    [ Interstate.GavelIcon,  'GavelIcon'],
    [ Interstate.GridSmallIcon,  'GridSmallIcon'],
    [ Interstate.GroundingSolidIcon,  'GroundingSolidIcon'],
    [ Interstate.HandThumbDownIcon,  'HandThumbDownIcon'],
    [ Interstate.HandThumbUpIcon,  'HandThumbUpIcon'],
    [ Interstate.HeartIcon,  'HeartSolidIcon'],
    [ Interstate.HeartIcon,  'HeartIcon'],
    [ Interstate.HomeIcon,  'HomeIcon'],
    [ Interstate.ImagesIcon,  'ImagesIcon'],
    [ Interstate.InboxArrowDownIcon,  'InboxArrowDownIcon'],
    [ Interstate.InformationCircleIcon,  'InformationCircleIcon'],
    [ Interstate.LinkIcon,  'LinkIcon'],
    [ Interstate.ListBulletIcon,  'ListBulletIcon'],
    [ Interstate.LocationAreaIcon,  'LocationAreaIcon'],
    [ Interstate.LockClosedIcon,  'LockClosedIcon'],
    [ Interstate.LockOpenIcon,  'LockOpenIcon'],
    [ Interstate.MagnifyingGlassIcon,  'MagnifyingGlassIcon'],
    [ Interstate.MagnifyingGlassMinusIcon,  'MagnifyingGlassMinusIcon'],
    [ Interstate.MagnifyingGlassPlusIcon,  'MagnifyingGlassPlusIcon'],
    [ Interstate.ManheimMedallionSolidIcon,  'ManheimMedallionSolidIcon'],
    [ Interstate.MapPinIcon,  'MapPinIcon'],
    [ Interstate.MedalSolidIcon,  'MedalSolidIcon'],
    [ Interstate.MegaphoneIcon,  'MegaphoneIcon'],
    [ Interstate.MinusCircleIcon,  'MinusCircleIcon'],
    [ Interstate.MinusIcon,  'MinusIcon'],
    [ Interstate.MinusSmallIcon,  'MinusSmallIcon'],
    [ Interstate.NoSymbolIcon,  'NoSymbolIcon'],
    [ Interstate.OdometerSolidIcon,  'OdometerSolidIcon'],
    [ Interstate.PaintCanIcon,  'PaintCanIcon'],
    [ Interstate.PaintDropSolidIcon,  'PaintDropSolidIcon'],
    [ Interstate.PaperClipIcon,  'PaperClipIcon'],
    [ Interstate.PauseCircleIcon,  'PauseCircleIcon'],
    [ Interstate.PencilSquareIcon,  'PencilSquareIcon'],
    [ Interstate.PhotoIcon,  'PhotoIcon'],
    [ Interstate.Pin2Icon,  'Pin2Icon'],
    [ Interstate.PinSolidIcon,  'PinSolidIcon'],
    [ Interstate.PlayCircleIcon,  'PlayCircleIcon'],
    [ Interstate.PlusCircleIcon,  'PlusCircleIcon'],
    [ Interstate.PlusIcon,  'PlusIcon'],
    [ Interstate.PlusSmallIcon,  'PlusSmallIcon'],
    [ Interstate.PrinterIcon,  'PrinterIcon'],
    [ Interstate.ProfileCcwCircleArrowIcon,  'ProfileCcwCircleArrowIcon'],
    [ Interstate.QrCodeIcon,  'QrCodeIcon'],
    [ Interstate.ResetTimeIcon,  'ResetTimeIcon'],
    [ Interstate.SeatsIcon,  'SeatsIcon'],
    [ Interstate.ShieldCheckIcon,  'ShieldCheckIcon'],
    [ Interstate.ShieldSolidIcon,  'ShieldSolidIcon'],
    [ Interstate.SpeakerWaveIcon,  'SpeakerWaveIcon'],
    [ Interstate.SpeakerXMarkIcon,  'SpeakerXMarkIcon'],
    [ Interstate.Squares2X2Icon,  'Squares2X2Icon'],
    [ Interstate.StarHalfSolidIcon,  'StarHalfSolidIcon'],
    [ Interstate.StarIcon,  'StarSolidIcon'],
    [ Interstate.StarIcon,  'StarIcon'],
    [ Interstate.SteeringWheelIcon,  'SteeringWheelIcon'],
    [ Interstate.StopwatchSolidIcon,  'StopwatchSolidIcon'],
    [ Interstate.TagIcon,  'TagIcon'],
    [ Interstate.ThreeSixtyExteriorSolidIcon,  'ThreeSixtyExteriorSolidIcon'],
    [ Interstate.ThreeSixtySolidIcon,  'ThreeSixtySolidIcon'],
    [ Interstate.ThreeSixtyInteriorFrontSolidIcon,  'ThreeSixtyInteriorFrontSolidIcon'],
    [ Interstate.ThreeSixtyInteriorRearSolidIcon,  'ThreeSixtyInteriorRearSolidIcon'],
    [ Interstate.TrashIcon,  'TrashIcon'],
    [ Interstate.TruckIcon,  'TruckIcon'],
    [ Interstate.UnlinkIcon,  'UnlinkIcon'],
    [ Interstate.UserCircleIcon,  'UserCircleIcon'],
    [ Interstate.UserIcon,  'UserIcon'],
    [ Interstate.UserPlusIcon,  'UserPlusIcon'],
    [ Interstate.UsersIcon,  'UsersIcon'],
    [ Interstate.VideoCameraIcon,  'VideoCameraIcon'],
    [ Interstate.WifiIcon,  'WifiIcon'],
    [ Interstate.XCircleIcon, 'XCircleIcon'],
    [ Interstate.XMarkIcon, 'XMarkIcon']
    
] as [React.FunctionComponent<React.ComponentProps<'svg'>>, string][];

const outlineList = [
    [Outline.AcademicCapIcon,'AcademicCapIcon'],
    [Outline.AdjustmentsHorizontalIcon,'AdjustmentsHorizontalIcon'],
    [Outline.AdjustmentsVerticalIcon,'AdjustmentsVerticalIcon'],
    [Outline.ArchiveBoxArrowDownIcon,'ArchiveBoxArrowDownIcon'],
    [Outline.ArchiveBoxIcon,'ArchiveBoxIcon'],
    [Outline.ArchiveBoxXMarkIcon,'ArchiveBoxXMarkIcon'],
    [Outline.ArrowDownCircleIcon,'ArrowDownCircleIcon'],
    [Outline.ArrowDownIcon,'ArrowDownIcon'],
    [Outline.ArrowDownLeftIcon,'ArrowDownLeftIcon'],
    [Outline.ArrowDownOnSquareIcon,'ArrowDownOnSquareIcon'],
    [Outline.ArrowDownOnSquareStackIcon,'ArrowDownOnSquareStackIcon'],
    [Outline.ArrowDownRightIcon,'ArrowDownRightIcon'],
    [Outline.ArrowDownTrayIcon,'ArrowDownTrayIcon'],
    [Outline.ArrowLeftCircleIcon,'ArrowLeftCircleIcon'],
    [Outline.ArrowLeftIcon,'ArrowLeftIcon'],
    [Outline.ArrowLeftOnRectangleIcon,'ArrowLeftOnRectangleIcon'],
    [Outline.ArrowLongDownIcon,'ArrowLongDownIcon'],
    [Outline.ArrowLongLeftIcon,'ArrowLongLeftIcon'],
    [Outline.ArrowLongRightIcon,'ArrowLongRightIcon'],
    [Outline.ArrowLongUpIcon,'ArrowLongUpIcon'],
    [Outline.ArrowPathIcon,'ArrowPathIcon'],
    [Outline.ArrowPathRoundedSquareIcon,'ArrowPathRoundedSquareIcon'],
    [Outline.ArrowRightCircleIcon,'ArrowRightCircleIcon'],
    [Outline.ArrowRightIcon,'ArrowRightIcon'],
    [Outline.ArrowRightOnRectangleIcon,'ArrowRightOnRectangleIcon'],
    [Outline.ArrowSmallDownIcon,'ArrowSmallDownIcon'],
    [Outline.ArrowSmallLeftIcon,'ArrowSmallLeftIcon'],
    [Outline.ArrowSmallRightIcon,'ArrowSmallRightIcon'],
    [Outline.ArrowSmallUpIcon,'ArrowSmallUpIcon'],
    [Outline.ArrowTopRightOnSquareIcon,'ArrowTopRightOnSquareIcon'],
    [Outline.ArrowTrendingDownIcon,'ArrowTrendingDownIcon'],
    [Outline.ArrowTrendingUpIcon,'ArrowTrendingUpIcon'],
    [Outline.ArrowUpCircleIcon,'ArrowUpCircleIcon'],
    [Outline.ArrowUpIcon,'ArrowUpIcon'],
    [Outline.ArrowUpLeftIcon,'ArrowUpLeftIcon'],
    [Outline.ArrowUpOnSquareIcon,'ArrowUpOnSquareIcon'],
    [Outline.ArrowUpOnSquareStackIcon,'ArrowUpOnSquareStackIcon'],
    [Outline.ArrowUpRightIcon,'ArrowUpRightIcon'],
    [Outline.ArrowUpTrayIcon,'ArrowUpTrayIcon'],
    [Outline.ArrowUturnDownIcon,'ArrowUturnDownIcon'],
    [Outline.ArrowUturnLeftIcon,'ArrowUturnLeftIcon'],
    [Outline.ArrowUturnRightIcon,'ArrowUturnRightIcon'],
    [Outline.ArrowUturnUpIcon,'ArrowUturnUpIcon'],
    [Outline.ArrowsPointingInIcon,'ArrowsPointingInIcon'],
    [Outline.ArrowsPointingOutIcon,'ArrowsPointingOutIcon'],
    [Outline.ArrowsRightLeftIcon,'ArrowsRightLeftIcon'],
    [Outline.ArrowsUpDownIcon,'ArrowsUpDownIcon'],
    [Outline.AtSymbolIcon,'AtSymbolIcon'],
    [Outline.BackspaceIcon,'BackspaceIcon'],
    [Outline.BackwardIcon,'BackwardIcon'],
    [Outline.BanknotesIcon,'BanknotesIcon'],
    [Outline.Bars2Icon,'Bars2Icon'],
    [Outline.Bars3BottomLeftIcon,'Bars3BottomLeftIcon'],
    [Outline.Bars3BottomRightIcon,'Bars3BottomRightIcon'],
    [Outline.Bars3CenterLeftIcon,'Bars3CenterLeftIcon'],
    [Outline.Bars3Icon,'Bars3Icon'],
    [Outline.Bars4Icon,'Bars4Icon'],
    [Outline.BarsArrowDownIcon,'BarsArrowDownIcon'],
    [Outline.BarsArrowUpIcon,'BarsArrowUpIcon'],
    [Outline.Battery0Icon,'Battery0Icon'],
    [Outline.Battery100Icon,'Battery100Icon'],
    [Outline.Battery50Icon,'Battery50Icon'],
    [Outline.BeakerIcon,'BeakerIcon'],
    [Outline.BellAlertIcon,'BellAlertIcon'],
    [Outline.BellIcon,'BellIcon'],
    [Outline.BellSlashIcon,'BellSlashIcon'],
    [Outline.BellSnoozeIcon,'BellSnoozeIcon'],
    [Outline.BoltIcon,'BoltIcon'],
    [Outline.BoltSlashIcon,'BoltSlashIcon'],
    [Outline.BookOpenIcon,'BookOpenIcon'],
    [Outline.BookmarkIcon,'BookmarkIcon'],
    [Outline.BookmarkSlashIcon,'BookmarkSlashIcon'],
    [Outline.BookmarkSquareIcon,'BookmarkSquareIcon'],
    [Outline.BriefcaseIcon,'BriefcaseIcon'],
    [Outline.BuildingLibraryIcon,'BuildingLibraryIcon'],
    [Outline.BuildingOffice2Icon,'BuildingOffice2Icon'],
    [Outline.BuildingOfficeIcon,'BuildingOfficeIcon'],
    [Outline.BuildingStorefrontIcon,'BuildingStorefrontIcon'],
    [Outline.CakeIcon,'CakeIcon'],
    [Outline.CalculatorIcon,'CalculatorIcon'],
    [Outline.CalendarDaysIcon,'CalendarDaysIcon'],
    [Outline.CalendarIcon,'CalendarIcon'],
    [Outline.CameraIcon,'CameraIcon'],
    [Outline.ChartBarIcon,'ChartBarIcon'],
    [Outline.ChartBarSquareIcon,'ChartBarSquareIcon'],
    [Outline.ChartPieIcon,'ChartPieIcon'],
    [Outline.ChatBubbleBottomCenterIcon,'ChatBubbleBottomCenterIcon'],
    [Outline.ChatBubbleBottomCenterTextIcon,'ChatBubbleBottomCenterTextIcon'],
    [Outline.ChatBubbleLeftEllipsisIcon,'ChatBubbleLeftEllipsisIcon'],
    [Outline.ChatBubbleLeftIcon,'ChatBubbleLeftIcon'],
    [Outline.ChatBubbleLeftRightIcon,'ChatBubbleLeftRightIcon'],
    [Outline.ChatBubbleOvalLeftEllipsisIcon,'ChatBubbleOvalLeftEllipsisIcon'],
    [Outline.ChatBubbleOvalLeftIcon,'ChatBubbleOvalLeftIcon'],
    [Outline.CheckBadgeIcon,'CheckBadgeIcon'],
    [Outline.CheckCircleIcon,'CheckCircleIcon'],
    [Outline.CheckIcon,'CheckIcon'],
    [Outline.ChevronDoubleDownIcon,'ChevronDoubleDownIcon'],
    [Outline.ChevronDoubleLeftIcon,'ChevronDoubleLeftIcon'],
    [Outline.ChevronDoubleRightIcon,'ChevronDoubleRightIcon'],
    [Outline.ChevronDoubleUpIcon,'ChevronDoubleUpIcon'],
    [Outline.ChevronDownIcon,'ChevronDownIcon'],
    [Outline.ChevronLeftIcon,'ChevronLeftIcon'],
    [Outline.ChevronRightIcon,'ChevronRightIcon'],
    [Outline.ChevronUpDownIcon,'ChevronUpDownIcon'],
    [Outline.ChevronUpIcon,'ChevronUpIcon'],
    [Outline.CircleStackIcon,'CircleStackIcon'],
    [Outline.ClipboardDocumentCheckIcon,'ClipboardDocumentCheckIcon'],
    [Outline.ClipboardDocumentIcon,'ClipboardDocumentIcon'],
    [Outline.ClipboardDocumentListIcon,'ClipboardDocumentListIcon'],
    [Outline.ClipboardIcon,'ClipboardIcon'],
    [Outline.ClockIcon,'ClockIcon'],
    [Outline.CloudArrowDownIcon,'CloudArrowDownIcon'],
    [Outline.CloudArrowUpIcon,'CloudArrowUpIcon'],
    [Outline.CloudIcon,'CloudIcon'],
    [Outline.CodeBracketIcon,'CodeBracketIcon'],
    [Outline.CodeBracketSquareIcon,'CodeBracketSquareIcon'],
    [Outline.Cog6ToothIcon,'Cog6ToothIcon'],
    [Outline.Cog8ToothIcon,'Cog8ToothIcon'],
    [Outline.CogIcon,'CogIcon'],
    [Outline.CommandLineIcon,'CommandLineIcon'],
    [Outline.ComputerDesktopIcon,'ComputerDesktopIcon'],
    [Outline.CpuChipIcon,'CpuChipIcon'],
    [Outline.CreditCardIcon,'CreditCardIcon'],
    [Outline.CubeIcon,'CubeIcon'],
    [Outline.CubeTransparentIcon,'CubeTransparentIcon'],
    [Outline.CurrencyBangladeshiIcon,'CurrencyBangladeshiIcon'],
    [Outline.CurrencyDollarIcon,'CurrencyDollarIcon'],
    [Outline.CurrencyEuroIcon,'CurrencyEuroIcon'],
    [Outline.CurrencyPoundIcon,'CurrencyPoundIcon'],
    [Outline.CurrencyRupeeIcon,'CurrencyRupeeIcon'],
    [Outline.CurrencyYenIcon,'CurrencyYenIcon'],
    [Outline.CursorArrowRaysIcon,'CursorArrowRaysIcon'],
    [Outline.CursorArrowRippleIcon,'CursorArrowRippleIcon'],
    [Outline.DevicePhoneMobileIcon,'DevicePhoneMobileIcon'],
    [Outline.DeviceTabletIcon,'DeviceTabletIcon'],
    [Outline.DocumentArrowDownIcon,'DocumentArrowDownIcon'],
    [Outline.DocumentArrowUpIcon,'DocumentArrowUpIcon'],
    [Outline.DocumentChartBarIcon,'DocumentChartBarIcon'],
    [Outline.DocumentCheckIcon,'DocumentCheckIcon'],
    [Outline.DocumentDuplicateIcon,'DocumentDuplicateIcon'],
    [Outline.DocumentIcon,'DocumentIcon'],
    [Outline.DocumentMagnifyingGlassIcon,'DocumentMagnifyingGlassIcon'],
    [Outline.DocumentMinusIcon,'DocumentMinusIcon'],
    [Outline.DocumentPlusIcon,'DocumentPlusIcon'],
    [Outline.DocumentTextIcon,'DocumentTextIcon'],
    [Outline.EllipsisHorizontalCircleIcon,'EllipsisHorizontalCircleIcon'],
    [Outline.EllipsisHorizontalIcon,'EllipsisHorizontalIcon'],
    [Outline.EllipsisVerticalIcon,'EllipsisVerticalIcon'],
    [Outline.EnvelopeIcon,'EnvelopeIcon'],
    [Outline.EnvelopeOpenIcon,'EnvelopeOpenIcon'],
    [Outline.ExclamationCircleIcon,'ExclamationCircleIcon'],
    [Outline.ExclamationTriangleIcon,'ExclamationTriangleIcon'],
    [Outline.EyeIcon,'EyeIcon'],
    [Outline.EyeSlashIcon,'EyeSlashIcon'],
    [Outline.FaceFrownIcon,'FaceFrownIcon'],
    [Outline.FaceSmileIcon,'FaceSmileIcon'],
    [Outline.FilmIcon,'FilmIcon'],
    [Outline.FingerPrintIcon,'FingerPrintIcon'],
    [Outline.FireIcon,'FireIcon'],
    [Outline.FlagIcon,'FlagIcon'],
    [Outline.FolderArrowDownIcon,'FolderArrowDownIcon'],
    [Outline.FolderIcon,'FolderIcon'],
    [Outline.FolderMinusIcon,'FolderMinusIcon'],
    [Outline.FolderOpenIcon,'FolderOpenIcon'],
    [Outline.FolderPlusIcon,'FolderPlusIcon'],
    [Outline.ForwardIcon,'ForwardIcon'],
    [Outline.FunnelIcon,'FunnelIcon'],
    [Outline.GifIcon,'GifIcon'],
    [Outline.GiftIcon,'GiftIcon'],
    [Outline.GiftTopIcon,'GiftTopIcon'],
    [Outline.GlobeAltIcon,'GlobeAltIcon'],
    [Outline.GlobeAmericasIcon,'GlobeAmericasIcon'],
    [Outline.GlobeAsiaAustraliaIcon,'GlobeAsiaAustraliaIcon'],
    [Outline.GlobeEuropeAfricaIcon,'GlobeEuropeAfricaIcon'],
    [Outline.HandRaisedIcon,'HandRaisedIcon'],
    [Outline.HandThumbDownIcon,'HandThumbDownIcon'],
    [Outline.HandThumbUpIcon,'HandThumbUpIcon'],
    [Outline.HashtagIcon,'HashtagIcon'],
    [Outline.HeartIcon,'HeartIcon'],
    [Outline.HomeIcon,'HomeIcon'],
    [Outline.HomeModernIcon,'HomeModernIcon'],
    [Outline.IdentificationIcon,'IdentificationIcon'],
    [Outline.InboxArrowDownIcon,'InboxArrowDownIcon'],
    [Outline.InboxIcon,'InboxIcon'],
    [Outline.InboxStackIcon,'InboxStackIcon'],
    [Outline.InformationCircleIcon,'InformationCircleIcon'],
    [Outline.KeyIcon,'KeyIcon'],
    [Outline.LanguageIcon,'LanguageIcon'],
    [Outline.LifebuoyIcon,'LifebuoyIcon'],
    [Outline.LightBulbIcon,'LightBulbIcon'],
    [Outline.LinkIcon,'LinkIcon'],
    [Outline.ListBulletIcon,'ListBulletIcon'],
    [Outline.LockClosedIcon,'LockClosedIcon'],
    [Outline.LockOpenIcon,'LockOpenIcon'],
    [Outline.MagnifyingGlassCircleIcon,'MagnifyingGlassCircleIcon'],
    [Outline.MagnifyingGlassIcon,'MagnifyingGlassIcon'],
    [Outline.MagnifyingGlassMinusIcon,'MagnifyingGlassMinusIcon'],
    [Outline.MagnifyingGlassPlusIcon,'MagnifyingGlassPlusIcon'],
    [Outline.MapIcon,'MapIcon'],
    [Outline.MapPinIcon,'MapPinIcon'],
    [Outline.MegaphoneIcon,'MegaphoneIcon'],
    [Outline.MicrophoneIcon,'MicrophoneIcon'],
    [Outline.MinusCircleIcon,'MinusCircleIcon'],
    [Outline.MinusIcon,'MinusIcon'],
    [Outline.MinusSmallIcon,'MinusSmallIcon'],
    [Outline.MoonIcon,'MoonIcon'],
    [Outline.MusicalNoteIcon,'MusicalNoteIcon'],
    [Outline.NewspaperIcon,'NewspaperIcon'],
    [Outline.NoSymbolIcon,'NoSymbolIcon'],
    [Outline.PaintBrushIcon,'PaintBrushIcon'],
    [Outline.PaperAirplaneIcon,'PaperAirplaneIcon'],
    [Outline.PaperClipIcon,'PaperClipIcon'],
    [Outline.PauseIcon,'PauseIcon'],
    [Outline.PencilIcon,'PencilIcon'],
    [Outline.PencilSquareIcon,'PencilSquareIcon'],
    [Outline.PhoneArrowDownLeftIcon,'PhoneArrowDownLeftIcon'],
    [Outline.PhoneArrowUpRightIcon,'PhoneArrowUpRightIcon'],
    [Outline.PhoneIcon,'PhoneIcon'],
    [Outline.PhoneXMarkIcon,'PhoneXMarkIcon'],
    [Outline.PhotoIcon,'PhotoIcon'],
    [Outline.PlayIcon,'PlayIcon'],
    [Outline.PlayPauseIcon,'PlayPauseIcon'],
    [Outline.PlusCircleIcon,'PlusCircleIcon'],
    [Outline.PlusIcon,'PlusIcon'],
    [Outline.PlusSmallIcon,'PlusSmallIcon'],
    [Outline.PresentationChartBarIcon,'PresentationChartBarIcon'],
    [Outline.PresentationChartLineIcon,'PresentationChartLineIcon'],
    [Outline.PrinterIcon,'PrinterIcon'],
    [Outline.PuzzlePieceIcon,'PuzzlePieceIcon'],
    [Outline.QrCodeIcon,'QrCodeIcon'],
    [Outline.QuestionMarkCircleIcon,'QuestionMarkCircleIcon'],
    [Outline.QueueListIcon,'QueueListIcon'],
    [Outline.RadioIcon,'RadioIcon'],
    [Outline.ReceiptPercentIcon,'ReceiptPercentIcon'],
    [Outline.ReceiptRefundIcon,'ReceiptRefundIcon'],
    [Outline.RectangleGroupIcon,'RectangleGroupIcon'],
    [Outline.RectangleStackIcon,'RectangleStackIcon'],
    [Outline.RssIcon,'RssIcon'],
    [Outline.ScaleIcon,'ScaleIcon'],
    [Outline.ScissorsIcon,'ScissorsIcon'],
    [Outline.ServerIcon,'ServerIcon'],
    [Outline.ServerStackIcon,'ServerStackIcon'],
    [Outline.ShareIcon,'ShareIcon'],
    [Outline.ShieldCheckIcon,'ShieldCheckIcon'],
    [Outline.ShieldExclamationIcon,'ShieldExclamationIcon'],
    [Outline.ShoppingBagIcon,'ShoppingBagIcon'],
    [Outline.ShoppingCartIcon,'ShoppingCartIcon'],
    [Outline.SignalIcon,'SignalIcon'],
    [Outline.SignalSlashIcon,'SignalSlashIcon'],
    [Outline.SparklesIcon,'SparklesIcon'],
    [Outline.SpeakerWaveIcon,'SpeakerWaveIcon'],
    [Outline.SpeakerXMarkIcon,'SpeakerXMarkIcon'],
    [Outline.Square2StackIcon,'Square2StackIcon'],
    [Outline.Squares2X2Icon,'Squares2X2Icon'],
    [Outline.SquaresPlusIcon,'SquaresPlusIcon'],
    [Outline.StarIcon,'StarIcon'],
    [Outline.StopIcon,'StopIcon'],
    [Outline.SunIcon,'SunIcon'],
    [Outline.SwatchIcon,'SwatchIcon'],
    [Outline.TableCellsIcon,'TableCellsIcon'],
    [Outline.TagIcon,'TagIcon'],
    [Outline.TicketIcon,'TicketIcon'],
    [Outline.TrashIcon,'TrashIcon'],
    [Outline.TruckIcon,'TruckIcon'],
    [Outline.UserCircleIcon,'UserCircleIcon'],
    [Outline.UserGroupIcon,'UserGroupIcon'],
    [Outline.UserIcon,'UserIcon'],
    [Outline.UserMinusIcon,'UserMinusIcon'],
    [Outline.UserPlusIcon,'UserPlusIcon'],
    [Outline.UsersIcon,'UsersIcon'],
    [Outline.VariableIcon,'VariableIcon'],
    [Outline.VideoCameraIcon,'VideoCameraIcon'],
    [Outline.VideoCameraSlashIcon,'VideoCameraSlashIcon'],
    [Outline.ViewColumnsIcon,'ViewColumnsIcon'],
    [Outline.WalletIcon,'WalletIcon'],
    [Outline.WifiIcon,'WifiIcon'],
    [Outline.WrenchIcon,'WrenchIcon'],
    [Outline.WrenchScrewdriverIcon,'WrenchScrewdriverIcon'],
    [Outline.XCircleIcon,'XCircleIcon'],
    [Outline.XMarkIcon,'XMarkIcon'],
] as [React.FunctionComponent<React.ComponentProps<'svg'>>, string][]

const solidList = [
    [Solid.AcademicCapIcon,'AcademicCapIcon'],
    [Solid.AdjustmentsHorizontalIcon,'AdjustmentsHorizontalIcon'],
    [Solid.AdjustmentsVerticalIcon,'AdjustmentsVerticalIcon'],
    [Solid.ArchiveBoxArrowDownIcon,'ArchiveBoxArrowDownIcon'],
    [Solid.ArchiveBoxIcon,'ArchiveBoxIcon'],
    [Solid.ArchiveBoxXMarkIcon,'ArchiveBoxXMarkIcon'],
    [Solid.ArrowDownCircleIcon,'ArrowDownCircleIcon'],
    [Solid.ArrowDownIcon,'ArrowDownIcon'],
    [Solid.ArrowDownLeftIcon,'ArrowDownLeftIcon'],
    [Solid.ArrowDownOnSquareIcon,'ArrowDownOnSquareIcon'],
    [Solid.ArrowDownOnSquareStackIcon,'ArrowDownOnSquareStackIcon'],
    [Solid.ArrowDownRightIcon,'ArrowDownRightIcon'],
    [Solid.ArrowDownTrayIcon,'ArrowDownTrayIcon'],
    [Solid.ArrowLeftCircleIcon,'ArrowLeftCircleIcon'],
    [Solid.ArrowLeftIcon,'ArrowLeftIcon'],
    [Solid.ArrowLeftOnRectangleIcon,'ArrowLeftOnRectangleIcon'],
    [Solid.ArrowLongDownIcon,'ArrowLongDownIcon'],
    [Solid.ArrowLongLeftIcon,'ArrowLongLeftIcon'],
    [Solid.ArrowLongRightIcon,'ArrowLongRightIcon'],
    [Solid.ArrowLongUpIcon,'ArrowLongUpIcon'],
    [Solid.ArrowPathIcon,'ArrowPathIcon'],
    [Solid.ArrowPathRoundedSquareIcon,'ArrowPathRoundedSquareIcon'],
    [Solid.ArrowRightCircleIcon,'ArrowRightCircleIcon'],
    [Solid.ArrowRightIcon,'ArrowRightIcon'],
    [Solid.ArrowRightOnRectangleIcon,'ArrowRightOnRectangleIcon'],
    [Solid.ArrowSmallDownIcon,'ArrowSmallDownIcon'],
    [Solid.ArrowSmallLeftIcon,'ArrowSmallLeftIcon'],
    [Solid.ArrowSmallRightIcon,'ArrowSmallRightIcon'],
    [Solid.ArrowSmallUpIcon,'ArrowSmallUpIcon'],
    [Solid.ArrowTopRightOnSquareIcon,'ArrowTopRightOnSquareIcon'],
    [Solid.ArrowTrendingDownIcon,'ArrowTrendingDownIcon'],
    [Solid.ArrowTrendingUpIcon,'ArrowTrendingUpIcon'],
    [Solid.ArrowUpCircleIcon,'ArrowUpCircleIcon'],
    [Solid.ArrowUpIcon,'ArrowUpIcon'],
    [Solid.ArrowUpLeftIcon,'ArrowUpLeftIcon'],
    [Solid.ArrowUpOnSquareIcon,'ArrowUpOnSquareIcon'],
    [Solid.ArrowUpOnSquareStackIcon,'ArrowUpOnSquareStackIcon'],
    [Solid.ArrowUpRightIcon,'ArrowUpRightIcon'],
    [Solid.ArrowUpTrayIcon,'ArrowUpTrayIcon'],
    [Solid.ArrowUturnDownIcon,'ArrowUturnDownIcon'],
    [Solid.ArrowUturnLeftIcon,'ArrowUturnLeftIcon'],
    [Solid.ArrowUturnRightIcon,'ArrowUturnRightIcon'],
    [Solid.ArrowUturnUpIcon,'ArrowUturnUpIcon'],
    [Solid.ArrowsPointingInIcon,'ArrowsPointingInIcon'],
    [Solid.ArrowsPointingOutIcon,'ArrowsPointingOutIcon'],
    [Solid.ArrowsRightLeftIcon,'ArrowsRightLeftIcon'],
    [Solid.ArrowsUpDownIcon,'ArrowsUpDownIcon'],
    [Solid.AtSymbolIcon,'AtSymbolIcon'],
    [Solid.BackspaceIcon,'BackspaceIcon'],
    [Solid.BackwardIcon,'BackwardIcon'],
    [Solid.BanknotesIcon,'BanknotesIcon'],
    [Solid.Bars2Icon,'Bars2Icon'],
    [Solid.Bars3BottomLeftIcon,'Bars3BottomLeftIcon'],
    [Solid.Bars3BottomRightIcon,'Bars3BottomRightIcon'],
    [Solid.Bars3CenterLeftIcon,'Bars3CenterLeftIcon'],
    [Solid.Bars3Icon,'Bars3Icon'],
    [Solid.Bars4Icon,'Bars4Icon'],
    [Solid.BarsArrowDownIcon,'BarsArrowDownIcon'],
    [Solid.BarsArrowUpIcon,'BarsArrowUpIcon'],
    [Solid.Battery0Icon,'Battery0Icon'],
    [Solid.Battery100Icon,'Battery100Icon'],
    [Solid.Battery50Icon,'Battery50Icon'],
    [Solid.BeakerIcon,'BeakerIcon'],
    [Solid.BellAlertIcon,'BellAlertIcon'],
    [Solid.BellIcon,'BellIcon'],
    [Solid.BellSlashIcon,'BellSlashIcon'],
    [Solid.BellSnoozeIcon,'BellSnoozeIcon'],
    [Solid.BoltIcon,'BoltIcon'],
    [Solid.BoltSlashIcon,'BoltSlashIcon'],
    [Solid.BookOpenIcon,'BookOpenIcon'],
    [Solid.BookmarkIcon,'BookmarkIcon'],
    [Solid.BookmarkSlashIcon,'BookmarkSlashIcon'],
    [Solid.BookmarkSquareIcon,'BookmarkSquareIcon'],
    [Solid.BriefcaseIcon,'BriefcaseIcon'],
    [Solid.BuildingLibraryIcon,'BuildingLibraryIcon'],
    [Solid.BuildingOffice2Icon,'BuildingOffice2Icon'],
    [Solid.BuildingOfficeIcon,'BuildingOfficeIcon'],
    [Solid.BuildingStorefrontIcon,'BuildingStorefrontIcon'],
    [Solid.CakeIcon,'CakeIcon'],
    [Solid.CalculatorIcon,'CalculatorIcon'],
    [Solid.CalendarDaysIcon,'CalendarDaysIcon'],
    [Solid.CalendarIcon,'CalendarIcon'],
    [Solid.CameraIcon,'CameraIcon'],
    [Solid.ChartBarIcon,'ChartBarIcon'],
    [Solid.ChartBarSquareIcon,'ChartBarSquareIcon'],
    [Solid.ChartPieIcon,'ChartPieIcon'],
    [Solid.ChatBubbleBottomCenterIcon,'ChatBubbleBottomCenterIcon'],
    [Solid.ChatBubbleBottomCenterTextIcon,'ChatBubbleBottomCenterTextIcon'],
    [Solid.ChatBubbleLeftEllipsisIcon,'ChatBubbleLeftEllipsisIcon'],
    [Solid.ChatBubbleLeftIcon,'ChatBubbleLeftIcon'],
    [Solid.ChatBubbleLeftRightIcon,'ChatBubbleLeftRightIcon'],
    [Solid.ChatBubbleOvalLeftEllipsisIcon,'ChatBubbleOvalLeftEllipsisIcon'],
    [Solid.ChatBubbleOvalLeftIcon,'ChatBubbleOvalLeftIcon'],
    [Solid.CheckBadgeIcon,'CheckBadgeIcon'],
    [Solid.CheckCircleIcon,'CheckCircleIcon'],
    [Solid.CheckIcon,'CheckIcon'],
    [Solid.ChevronDoubleDownIcon,'ChevronDoubleDownIcon'],
    [Solid.ChevronDoubleLeftIcon,'ChevronDoubleLeftIcon'],
    [Solid.ChevronDoubleRightIcon,'ChevronDoubleRightIcon'],
    [Solid.ChevronDoubleUpIcon,'ChevronDoubleUpIcon'],
    [Solid.ChevronDownIcon,'ChevronDownIcon'],
    [Solid.ChevronLeftIcon,'ChevronLeftIcon'],
    [Solid.ChevronRightIcon,'ChevronRightIcon'],
    [Solid.ChevronUpDownIcon,'ChevronUpDownIcon'],
    [Solid.ChevronUpIcon,'ChevronUpIcon'],
    [Solid.CircleStackIcon,'CircleStackIcon'],
    [Solid.ClipboardDocumentCheckIcon,'ClipboardDocumentCheckIcon'],
    [Solid.ClipboardDocumentIcon,'ClipboardDocumentIcon'],
    [Solid.ClipboardDocumentListIcon,'ClipboardDocumentListIcon'],
    [Solid.ClipboardIcon,'ClipboardIcon'],
    [Solid.ClockIcon,'ClockIcon'],
    [Solid.CloudArrowDownIcon,'CloudArrowDownIcon'],
    [Solid.CloudArrowUpIcon,'CloudArrowUpIcon'],
    [Solid.CloudIcon,'CloudIcon'],
    [Solid.CodeBracketIcon,'CodeBracketIcon'],
    [Solid.CodeBracketSquareIcon,'CodeBracketSquareIcon'],
    [Solid.Cog6ToothIcon,'Cog6ToothIcon'],
    [Solid.Cog8ToothIcon,'Cog8ToothIcon'],
    [Solid.CogIcon,'CogIcon'],
    [Solid.CommandLineIcon,'CommandLineIcon'],
    [Solid.ComputerDesktopIcon,'ComputerDesktopIcon'],
    [Solid.CpuChipIcon,'CpuChipIcon'],
    [Solid.CreditCardIcon,'CreditCardIcon'],
    [Solid.CubeIcon,'CubeIcon'],
    [Solid.CubeTransparentIcon,'CubeTransparentIcon'],
    [Solid.CurrencyBangladeshiIcon,'CurrencyBangladeshiIcon'],
    [Solid.CurrencyDollarIcon,'CurrencyDollarIcon'],
    [Solid.CurrencyEuroIcon,'CurrencyEuroIcon'],
    [Solid.CurrencyPoundIcon,'CurrencyPoundIcon'],
    [Solid.CurrencyRupeeIcon,'CurrencyRupeeIcon'],
    [Solid.CurrencyYenIcon,'CurrencyYenIcon'],
    [Solid.CursorArrowRaysIcon,'CursorArrowRaysIcon'],
    [Solid.CursorArrowRippleIcon,'CursorArrowRippleIcon'],
    [Solid.DevicePhoneMobileIcon,'DevicePhoneMobileIcon'],
    [Solid.DeviceTabletIcon,'DeviceTabletIcon'],
    [Solid.DocumentArrowDownIcon,'DocumentArrowDownIcon'],
    [Solid.DocumentArrowUpIcon,'DocumentArrowUpIcon'],
    [Solid.DocumentChartBarIcon,'DocumentChartBarIcon'],
    [Solid.DocumentCheckIcon,'DocumentCheckIcon'],
    [Solid.DocumentDuplicateIcon,'DocumentDuplicateIcon'],
    [Solid.DocumentIcon,'DocumentIcon'],
    [Solid.DocumentMagnifyingGlassIcon,'DocumentMagnifyingGlassIcon'],
    [Solid.DocumentMinusIcon,'DocumentMinusIcon'],
    [Solid.DocumentPlusIcon,'DocumentPlusIcon'],
    [Solid.DocumentTextIcon,'DocumentTextIcon'],
    [Solid.EllipsisHorizontalCircleIcon,'EllipsisHorizontalCircleIcon'],
    [Solid.EllipsisHorizontalIcon,'EllipsisHorizontalIcon'],
    [Solid.EllipsisVerticalIcon,'EllipsisVerticalIcon'],
    [Solid.EnvelopeIcon,'EnvelopeIcon'],
    [Solid.EnvelopeOpenIcon,'EnvelopeOpenIcon'],
    [Solid.ExclamationCircleIcon,'ExclamationCircleIcon'],
    [Solid.ExclamationTriangleIcon,'ExclamationTriangleIcon'],
    [Solid.EyeIcon,'EyeIcon'],
    [Solid.EyeSlashIcon,'EyeSlashIcon'],
    [Solid.FaceFrownIcon,'FaceFrownIcon'],
    [Solid.FaceSmileIcon,'FaceSmileIcon'],
    [Solid.FilmIcon,'FilmIcon'],
    [Solid.FingerPrintIcon,'FingerPrintIcon'],
    [Solid.FireIcon,'FireIcon'],
    [Solid.FlagIcon,'FlagIcon'],
    [Solid.FolderArrowDownIcon,'FolderArrowDownIcon'],
    [Solid.FolderIcon,'FolderIcon'],
    [Solid.FolderMinusIcon,'FolderMinusIcon'],
    [Solid.FolderOpenIcon,'FolderOpenIcon'],
    [Solid.FolderPlusIcon,'FolderPlusIcon'],
    [Solid.ForwardIcon,'ForwardIcon'],
    [Solid.FunnelIcon,'FunnelIcon'],
    [Solid.GifIcon,'GifIcon'],
    [Solid.GiftIcon,'GiftIcon'],
    [Solid.GiftTopIcon,'GiftTopIcon'],
    [Solid.GlobeAltIcon,'GlobeAltIcon'],
    [Solid.GlobeAmericasIcon,'GlobeAmericasIcon'],
    [Solid.GlobeAsiaAustraliaIcon,'GlobeAsiaAustraliaIcon'],
    [Solid.GlobeEuropeAfricaIcon,'GlobeEuropeAfricaIcon'],
    [Solid.HandRaisedIcon,'HandRaisedIcon'],
    [Solid.HandThumbDownIcon,'HandThumbDownIcon'],
    [Solid.HandThumbUpIcon,'HandThumbUpIcon'],
    [Solid.HashtagIcon,'HashtagIcon'],
    [Solid.HeartIcon,'HeartIcon'],
    [Solid.HomeIcon,'HomeIcon'],
    [Solid.HomeModernIcon,'HomeModernIcon'],
    [Solid.IdentificationIcon,'IdentificationIcon'],
    [Solid.InboxArrowDownIcon,'InboxArrowDownIcon'],
    [Solid.InboxIcon,'InboxIcon'],
    [Solid.InboxStackIcon,'InboxStackIcon'],
    [Solid.InformationCircleIcon,'InformationCircleIcon'],
    [Solid.KeyIcon,'KeyIcon'],
    [Solid.LanguageIcon,'LanguageIcon'],
    [Solid.LifebuoyIcon,'LifebuoyIcon'],
    [Solid.LightBulbIcon,'LightBulbIcon'],
    [Solid.LinkIcon,'LinkIcon'],
    [Solid.ListBulletIcon,'ListBulletIcon'],
    [Solid.LockClosedIcon,'LockClosedIcon'],
    [Solid.LockOpenIcon,'LockOpenIcon'],
    [Solid.MagnifyingGlassCircleIcon,'MagnifyingGlassCircleIcon'],
    [Solid.MagnifyingGlassIcon,'MagnifyingGlassIcon'],
    [Solid.MagnifyingGlassMinusIcon,'MagnifyingGlassMinusIcon'],
    [Solid.MagnifyingGlassPlusIcon,'MagnifyingGlassPlusIcon'],
    [Solid.MapIcon,'MapIcon'],
    [Solid.MapPinIcon,'MapPinIcon'],
    [Solid.MegaphoneIcon,'MegaphoneIcon'],
    [Solid.MicrophoneIcon,'MicrophoneIcon'],
    [Solid.MinusCircleIcon,'MinusCircleIcon'],
    [Solid.MinusIcon,'MinusIcon'],
    [Solid.MinusSmallIcon,'MinusSmallIcon'],
    [Solid.MoonIcon,'MoonIcon'],
    [Solid.MusicalNoteIcon,'MusicalNoteIcon'],
    [Solid.NewspaperIcon,'NewspaperIcon'],
    [Solid.NoSymbolIcon,'NoSymbolIcon'],
    [Solid.PaintBrushIcon,'PaintBrushIcon'],
    [Solid.PaperAirplaneIcon,'PaperAirplaneIcon'],
    [Solid.PaperClipIcon,'PaperClipIcon'],
    [Solid.PauseIcon,'PauseIcon'],
    [Solid.PencilIcon,'PencilIcon'],
    [Solid.PencilSquareIcon,'PencilSquareIcon'],
    [Solid.PhoneArrowDownLeftIcon,'PhoneArrowDownLeftIcon'],
    [Solid.PhoneArrowUpRightIcon,'PhoneArrowUpRightIcon'],
    [Solid.PhoneIcon,'PhoneIcon'],
    [Solid.PhoneXMarkIcon,'PhoneXMarkIcon'],
    [Solid.PhotoIcon,'PhotoIcon'],
    [Solid.PlayIcon,'PlayIcon'],
    [Solid.PlayPauseIcon,'PlayPauseIcon'],
    [Solid.PlusCircleIcon,'PlusCircleIcon'],
    [Solid.PlusIcon,'PlusIcon'],
    [Solid.PlusSmallIcon,'PlusSmallIcon'],
    [Solid.PresentationChartBarIcon,'PresentationChartBarIcon'],
    [Solid.PresentationChartLineIcon,'PresentationChartLineIcon'],
    [Solid.PrinterIcon,'PrinterIcon'],
    [Solid.PuzzlePieceIcon,'PuzzlePieceIcon'],
    [Solid.QrCodeIcon,'QrCodeIcon'],
    [Solid.QuestionMarkCircleIcon,'QuestionMarkCircleIcon'],
    [Solid.QueueListIcon,'QueueListIcon'],
    [Solid.RadioIcon,'RadioIcon'],
    [Solid.ReceiptPercentIcon,'ReceiptPercentIcon'],
    [Solid.ReceiptRefundIcon,'ReceiptRefundIcon'],
    [Solid.RectangleGroupIcon,'RectangleGroupIcon'],
    [Solid.RectangleStackIcon,'RectangleStackIcon'],
    [Solid.RssIcon,'RssIcon'],
    [Solid.ScaleIcon,'ScaleIcon'],
    [Solid.ScissorsIcon,'ScissorsIcon'],
    [Solid.ServerIcon,'ServerIcon'],
    [Solid.ServerStackIcon,'ServerStackIcon'],
    [Solid.ShareIcon,'ShareIcon'],
    [Solid.ShieldCheckIcon,'ShieldCheckIcon'],
    [Solid.ShieldExclamationIcon,'ShieldExclamationIcon'],
    [Solid.ShoppingBagIcon,'ShoppingBagIcon'],
    [Solid.ShoppingCartIcon,'ShoppingCartIcon'],
    [Solid.SignalIcon,'SignalIcon'],
    [Solid.SignalSlashIcon,'SignalSlashIcon'],
    [Solid.SparklesIcon,'SparklesIcon'],
    [Solid.SpeakerWaveIcon,'SpeakerWaveIcon'],
    [Solid.SpeakerXMarkIcon,'SpeakerXMarkIcon'],
    [Solid.Square2StackIcon,'Square2StackIcon'],
    [Solid.Squares2X2Icon,'Squares2X2Icon'],
    [Solid.SquaresPlusIcon,'SquaresPlusIcon'],
    [Solid.StarIcon,'StarIcon'],
    [Solid.StopIcon,'StopIcon'],
    [Solid.SunIcon,'SunIcon'],
    [Solid.SwatchIcon,'SwatchIcon'],
    [Solid.TableCellsIcon,'TableCellsIcon'],
    [Solid.TagIcon,'TagIcon'],
    [Solid.TicketIcon,'TicketIcon'],
    [Solid.TrashIcon,'TrashIcon'],
    [Solid.TruckIcon,'TruckIcon'],
    [Solid.UserCircleIcon,'UserCircleIcon'],
    [Solid.UserGroupIcon,'UserGroupIcon'],
    [Solid.UserIcon,'UserIcon'],
    [Solid.UserMinusIcon,'UserMinusIcon'],
    [Solid.UserPlusIcon,'UserPlusIcon'],
    [Solid.UsersIcon,'UsersIcon'],
    [Solid.VariableIcon,'VariableIcon'],
    [Solid.VideoCameraIcon,'VideoCameraIcon'],
    [Solid.VideoCameraSlashIcon,'VideoCameraSlashIcon'],
    [Solid.ViewColumnsIcon,'ViewColumnsIcon'],
    [Solid.WalletIcon,'WalletIcon'],
    [Solid.WifiIcon,'WifiIcon'],
    [Solid.WrenchIcon,'WrenchIcon'],
    [Solid.WrenchScrewdriverIcon,'WrenchScrewdriverIcon'],
    [Solid.XCircleIcon,'XCircleIcon'],
    [Solid.XMarkIcon,'XMarkIcon'],
] as [React.FunctionComponent<React.ComponentProps<'svg'>>, string][]

const prismList = [
    [P2.ThreeSixtyIcon, 'ThreeSixtyIcon'],
    [P2.ThreeSixtyExteriorIcon, 'ThreeSixtyExteriorIcon'],
    [P2.ThreeSixtyInteriorFrontIcon, 'ThreeSixtyInteriorFrontIcon'],
    [P2.ThreeSixtyInteriorRearIcon, 'ThreeSixtyInteriorRearIcon'],
    [P2.AlarmAddIcon, 'AlarmAddIcon'],
    [P2.AlarmClockIcon, 'AlarmClockIcon'],
    [P2.AlarmSetIcon, 'AlarmSetIcon'],
    [P2.ArrowDownIcon, 'ArrowDownIcon'],
    [P2.ArrowLeftIcon, 'ArrowLeftIcon'],
    [P2.ArrowRightIcon, 'ArrowRightIcon'],
    [P2.ArrowUpIcon, 'ArrowUpIcon'],
    [P2.ArrowsLeftRightIcon, 'ArrowsLeftRightIcon'],
    [P2.ArrowsUpDownIcon, 'ArrowsUpDownIcon'],
    [P2.AttachIcon, 'AttachIcon'],
    [P2.BackToStartIcon, 'BackToStartIcon'],
    [P2.BarcodeIcon, 'BarcodeIcon'],
    [P2.BellIcon, 'BellIcon'],
    [P2.BellOIcon, 'BellOIcon'],
    [P2.BlockedIcon, 'BlockedIcon'],
    [P2.BoltIcon, 'BoltIcon'],
    [P2.BubbleIcon, 'BubbleIcon'],
    [P2.BubblesIcon, 'BubblesIcon'],
    [P2.BulletIcon, 'BulletIcon'],
    [P2.CalendarIcon, 'CalendarIcon'],
    [P2.CamcorderIcon, 'CamcorderIcon'],
    [P2.CameraIcon, 'CameraIcon'],
    [P2.CancelCircleIcon, 'CancelCircleIcon'],
    [P2.CancelCircleOIcon, 'CancelCircleOIcon'],
    [P2.CarIcon, 'CarIcon'],
    [P2.CarSideIcon, 'CarSideIcon'],
    [P2.CheckboxCheckedIcon, 'CheckboxCheckedIcon'],
    [P2.CheckboxUncheckedIcon, 'CheckboxUncheckedIcon'],
    [P2.CheckmarkCircleIcon, 'CheckmarkCircleIcon'],
    [P2.CheckmarkIcon, 'CheckmarkIcon'],
    [P2.ChevronDownChamferedIcon, 'ChevronDownChamferedIcon'],
    [P2.ChevronDownIcon, 'ChevronDownIcon'],
    [P2.ChevronDownLightIcon, 'ChevronDownLightIcon'],
    [P2.ChevronLeftIcon, 'ChevronLeftIcon'],
    [P2.ChevronLeftLightIcon, 'ChevronLeftLightIcon'],
    [P2.ChevronRightIcon, 'ChevronRightIcon'],
    [P2.ChevronRightLightIcon, 'ChevronRightLightIcon'],
    [P2.ChevronUpIcon, 'ChevronUpIcon'],
    [P2.ChevronUpLightIcon, 'ChevronUpLightIcon'],
    [P2.ClipboardCheckedIcon, 'ClipboardCheckedIcon'],
    [P2.ClipboardIcon, 'ClipboardIcon'],
    [P2.ClockIcon, 'ClockIcon'],
    [P2.CloudUploadIcon, 'CloudUploadIcon'],
    [P2.ConditionReportIcon, 'ConditionReportIcon'],
    [P2.CreditCardIcon, 'CreditCardIcon'],
    [P2.CrossIcon, 'CrossIcon'],
    [P2.CrossSmallIcon, 'CrossSmallIcon'],
    [P2.CupIcon, 'CupIcon'],
    [P2.DamagesIcon, 'DamagesIcon'],
    [P2.DetailsIcon, 'DetailsIcon'],
    [P2.DirectionIcon, 'DirectionIcon'],
    [P2.DiskIcon, 'DiskIcon'],
    [P2.DollarOIcon, 'DollarOIcon'],
    [P2.DownloadIcon, 'DownloadIcon'],
    [P2.EditIcon, 'EditIcon'],
    [P2.EnlargeIcon, 'EnlargeIcon'],
    [P2.Envelop5Icon, 'Envelop5Icon'],
    [P2.Envelope2Icon, 'Envelope2Icon'],
    [P2.EnvelopeIcon, 'EnvelopeIcon'],
    [P2.ErrorTriangleIcon, 'ErrorTriangleIcon'],
    [P2.ExportIcon, 'ExportIcon'],
    [P2.EyeBlockedIcon, 'EyeBlockedIcon'],
    [P2.EyeIcon, 'EyeIcon'],
    [P2.FileEmptyIcon, 'FileEmptyIcon'],
    [P2.FileExcelIcon, 'FileExcelIcon'],
    [P2.FilePdfIcon, 'FilePdfIcon'],
    [P2.FileSpreadsheetIcon, 'FileSpreadsheetIcon'],
    [P2.FileTextIcon, 'FileTextIcon'],
    [P2.FilesEmptyIcon, 'FilesEmptyIcon'],
    [P2.FilterIcon, 'FilterIcon'],
    [P2.FlagIcon, 'FlagIcon'],
    [P2.ForkSpoonIcon, 'ForkSpoonIcon'],
    [P2.FuelIcon, 'FuelIcon'],
    [P2.GavelIcon, 'GavelIcon'],
    [P2.GearIcon, 'GearIcon'],
    [P2.GraphPieIcon, 'GraphPieIcon'],
    [P2.GridIcon, 'GridIcon'],
    [P2.GridSmallIcon, 'GridSmallIcon'],
    [P2.GroundingIcon, 'GroundingIcon'],
    [P2.HeartIcon, 'HeartIcon'],
    [P2.HeartOIcon, 'HeartOIcon'],
    [P2.HomeIcon, 'HomeIcon'],
    [P2.ImageIcon, 'ImageIcon'],
    [P2.ImagesIcon, 'ImagesIcon'],
    [P2.InboxIcon, 'InboxIcon'],
    [P2.InfoIcon, 'InfoIcon'],
    [P2.InfoOIcon, 'InfoOIcon'],
    [P2.LeaveIcon, 'LeaveIcon'],
    [P2.LeftRightIcon, 'LeftRightIcon'],
    [P2.LinkIcon, 'LinkIcon'],
    [P2.ListIcon, 'ListIcon'],
    [P2.LocationAreaIcon, 'LocationAreaIcon'],
    [P2.LocationIcon, 'LocationIcon'],
    [P2.LockedIcon, 'LockedIcon'],
    [P2.ManheimMedallionIcon, 'ManheimMedallionIcon'],
    [P2.MarkerIcon, 'MarkerIcon'],
    [P2.MedalIcon, 'MedalIcon'],
    [P2.MegaphoneIcon, 'MegaphoneIcon'],
    [P2.MenuIcon, 'MenuIcon'],
    [P2.Minus2Icon, 'Minus2Icon'],
    [P2.Minus3Icon, 'Minus3Icon'],
    [P2.MinusCircleIcon, 'MinusCircleIcon'],
    [P2.MinusCircleOIcon, 'MinusCircleOIcon'],
    [P2.MinusIcon, 'MinusIcon'],
    [P2.MobileIcon, 'MobileIcon'],
    [P2.NewWindowIcon, 'NewWindowIcon'],
    [P2.NotificationCircleIcon, 'NotificationCircleIcon'],
    [P2.OdometerIcon, 'OdometerIcon'],
    [P2.PaintCanIcon, 'PaintCanIcon'],
    [P2.PaintDropIcon, 'PaintDropIcon'],
    [P2.PauseIcon, 'PauseIcon'],
    [P2.Pin2Icon, 'Pin2Icon'],
    [P2.PinIcon, 'PinIcon'],
    [P2.PlayIcon, 'PlayIcon'],
    [P2.PlusCircleIcon, 'PlusCircleIcon'],
    [P2.PlusCircleOIcon, 'PlusCircleOIcon'],
    [P2.PlusIcon, 'PlusIcon'],
    [P2.PriceTagIcon, 'PriceTagIcon'],
    [P2.PrinterIcon, 'PrinterIcon'],
    [P2.ProfileCcwCircleArrowIcon, 'ProfileCcwCircleArrowIcon'],
    [P2.QrCodeIcon, 'QrCodeIcon'],
    [P2.RefreshIcon, 'RefreshIcon'],
    [P2.ResetTimeIcon, 'ResetTimeIcon'],
    [P2.RotateLeftIcon, 'RotateLeftIcon'],
    [P2.RotateRightIcon, 'RotateRightIcon'],
    [P2.SearchIcon, 'SearchIcon'],
    [P2.ShieldCheckIcon, 'ShieldCheckIcon'],
    [P2.ShieldIcon, 'ShieldIcon'],
    [P2.ShrinkIcon, 'ShrinkIcon'],
    [P2.SortIcon, 'SortIcon'],
    [P2.SoundOffIcon, 'SoundOffIcon'],
    [P2.SoundOnIcon, 'SoundOnIcon'],
    [P2.SpinnerIcon, 'SpinnerIcon'],
    [P2.StarEmptyIcon, 'StarEmptyIcon'],
    [P2.StarFullIcon, 'StarFullIcon'],
    [P2.StarHalfIcon, 'StarHalfIcon'],
    [P2.StopwatchIcon, 'StopwatchIcon'],
    [P2.ThreeBarsIcon, 'ThreeBarsIcon'],
    [P2.ThreeDotsHorizontalIcon, 'ThreeDotsHorizontalIcon'],
    [P2.ThreeDotsVerticalIcon, 'ThreeDotsVerticalIcon'],
    [P2.ThumbsDownIcon, 'ThumbsDownIcon'],
    [P2.ThumbsUpIcon, 'ThumbsUpIcon'],
    [P2.TrashIcon, 'TrashIcon'],
    [P2.TriangleDownIcon, 'TriangleDownIcon'],
    [P2.TriangleDownSmallIcon, 'TriangleDownSmallIcon'],
    [P2.TriangleLeftIcon, 'TriangleLeftIcon'],
    [P2.TriangleLeftSmallIcon, 'TriangleLeftSmallIcon'],
    [P2.TriangleRightIcon, 'TriangleRightIcon'],
    [P2.TriangleRightSmallIcon, 'TriangleRightSmallIcon'],
    [P2.TriangleUpIcon, 'TriangleUpIcon'],
    [P2.TriangleUpSmallIcon, 'TriangleUpSmallIcon'],
    [P2.TruckIcon, 'TruckIcon'],
    [P2.UnlinkIcon, 'UnlinkIcon'],
    [P2.UnlockedIcon, 'UnlockedIcon'],
    [P2.UploadIcon, 'UploadIcon'],
    [P2.UserAddIcon, 'UserAddIcon'],
    [P2.UserIcon, 'UserIcon'],
    [P2.UsersIcon, 'UsersIcon'],
    [P2.WifiIcon, 'WifiIcon'],
    [P2.ZoomInIcon, 'ZoomInIcon'],
    [P2.ZoomOutIcon, 'ZoomOutIcon'],
] as [React.FunctionComponent<React.ComponentProps<'svg'>>, string][]

const miniList = [
    [Mini.AcademicCapIcon,'AcademicCapIcon'],
    [Mini.AdjustmentsHorizontalIcon,'AdjustmentsHorizontalIcon'],
    [Mini.AdjustmentsVerticalIcon,'AdjustmentsVerticalIcon'],
    [Mini.ArchiveBoxArrowDownIcon,'ArchiveBoxArrowDownIcon'],
    [Mini.ArchiveBoxIcon,'ArchiveBoxIcon'],
    [Mini.ArchiveBoxXMarkIcon,'ArchiveBoxXMarkIcon'],
    [Mini.ArrowDownCircleIcon,'ArrowDownCircleIcon'],
    [Mini.ArrowDownIcon,'ArrowDownIcon'],
    [Mini.ArrowDownLeftIcon,'ArrowDownLeftIcon'],
    [Mini.ArrowDownOnSquareIcon,'ArrowDownOnSquareIcon'],
    [Mini.ArrowDownOnSquareStackIcon,'ArrowDownOnSquareStackIcon'],
    [Mini.ArrowDownRightIcon,'ArrowDownRightIcon'],
    [Mini.ArrowDownTrayIcon,'ArrowDownTrayIcon'],
    [Mini.ArrowLeftCircleIcon,'ArrowLeftCircleIcon'],
    [Mini.ArrowLeftIcon,'ArrowLeftIcon'],
    [Mini.ArrowLeftOnRectangleIcon,'ArrowLeftOnRectangleIcon'],
    [Mini.ArrowLongDownIcon,'ArrowLongDownIcon'],
    [Mini.ArrowLongLeftIcon,'ArrowLongLeftIcon'],
    [Mini.ArrowLongRightIcon,'ArrowLongRightIcon'],
    [Mini.ArrowLongUpIcon,'ArrowLongUpIcon'],
    [Mini.ArrowPathIcon,'ArrowPathIcon'],
    [Mini.ArrowPathRoundedSquareIcon,'ArrowPathRoundedSquareIcon'],
    [Mini.ArrowRightCircleIcon,'ArrowRightCircleIcon'],
    [Mini.ArrowRightIcon,'ArrowRightIcon'],
    [Mini.ArrowRightOnRectangleIcon,'ArrowRightOnRectangleIcon'],
    [Mini.ArrowSmallDownIcon,'ArrowSmallDownIcon'],
    [Mini.ArrowSmallLeftIcon,'ArrowSmallLeftIcon'],
    [Mini.ArrowSmallRightIcon,'ArrowSmallRightIcon'],
    [Mini.ArrowSmallUpIcon,'ArrowSmallUpIcon'],
    [Mini.ArrowTopRightOnSquareIcon,'ArrowTopRightOnSquareIcon'],
    [Mini.ArrowTrendingDownIcon,'ArrowTrendingDownIcon'],
    [Mini.ArrowTrendingUpIcon,'ArrowTrendingUpIcon'],
    [Mini.ArrowUpCircleIcon,'ArrowUpCircleIcon'],
    [Mini.ArrowUpIcon,'ArrowUpIcon'],
    [Mini.ArrowUpLeftIcon,'ArrowUpLeftIcon'],
    [Mini.ArrowUpOnSquareIcon,'ArrowUpOnSquareIcon'],
    [Mini.ArrowUpOnSquareStackIcon,'ArrowUpOnSquareStackIcon'],
    [Mini.ArrowUpRightIcon,'ArrowUpRightIcon'],
    [Mini.ArrowUpTrayIcon,'ArrowUpTrayIcon'],
    [Mini.ArrowUturnDownIcon,'ArrowUturnDownIcon'],
    [Mini.ArrowUturnLeftIcon,'ArrowUturnLeftIcon'],
    [Mini.ArrowUturnRightIcon,'ArrowUturnRightIcon'],
    [Mini.ArrowUturnUpIcon,'ArrowUturnUpIcon'],
    [Mini.ArrowsPointingInIcon,'ArrowsPointingInIcon'],
    [Mini.ArrowsPointingOutIcon,'ArrowsPointingOutIcon'],
    [Mini.ArrowsRightLeftIcon,'ArrowsRightLeftIcon'],
    [Mini.ArrowsUpDownIcon,'ArrowsUpDownIcon'],
    [Mini.AtSymbolIcon,'AtSymbolIcon'],
    [Mini.BackspaceIcon,'BackspaceIcon'],
    [Mini.BackwardIcon,'BackwardIcon'],
    [Mini.BanknotesIcon,'BanknotesIcon'],
    [Mini.Bars2Icon,'Bars2Icon'],
    [Mini.Bars3BottomLeftIcon,'Bars3BottomLeftIcon'],
    [Mini.Bars3BottomRightIcon,'Bars3BottomRightIcon'],
    [Mini.Bars3CenterLeftIcon,'Bars3CenterLeftIcon'],
    [Mini.Bars3Icon,'Bars3Icon'],
    [Mini.Bars4Icon,'Bars4Icon'],
    [Mini.BarsArrowDownIcon,'BarsArrowDownIcon'],
    [Mini.BarsArrowUpIcon,'BarsArrowUpIcon'],
    [Mini.Battery0Icon,'Battery0Icon'],
    [Mini.Battery100Icon,'Battery100Icon'],
    [Mini.Battery50Icon,'Battery50Icon'],
    [Mini.BeakerIcon,'BeakerIcon'],
    [Mini.BellAlertIcon,'BellAlertIcon'],
    [Mini.BellIcon,'BellIcon'],
    [Mini.BellSlashIcon,'BellSlashIcon'],
    [Mini.BellSnoozeIcon,'BellSnoozeIcon'],
    [Mini.BoltIcon,'BoltIcon'],
    [Mini.BoltSlashIcon,'BoltSlashIcon'],
    [Mini.BookOpenIcon,'BookOpenIcon'],
    [Mini.BookmarkIcon,'BookmarkIcon'],
    [Mini.BookmarkSlashIcon,'BookmarkSlashIcon'],
    [Mini.BookmarkSquareIcon,'BookmarkSquareIcon'],
    [Mini.BriefcaseIcon,'BriefcaseIcon'],
    [Mini.BuildingLibraryIcon,'BuildingLibraryIcon'],
    [Mini.BuildingOffice2Icon,'BuildingOffice2Icon'],
    [Mini.BuildingOfficeIcon,'BuildingOfficeIcon'],
    [Mini.BuildingStorefrontIcon,'BuildingStorefrontIcon'],
    [Mini.CakeIcon,'CakeIcon'],
    [Mini.CalculatorIcon,'CalculatorIcon'],
    [Mini.CalendarDaysIcon,'CalendarDaysIcon'],
    [Mini.CalendarIcon,'CalendarIcon'],
    [Mini.CameraIcon,'CameraIcon'],
    [Mini.ChartBarIcon,'ChartBarIcon'],
    [Mini.ChartBarSquareIcon,'ChartBarSquareIcon'],
    [Mini.ChartPieIcon,'ChartPieIcon'],
    [Mini.ChatBubbleBottomCenterIcon,'ChatBubbleBottomCenterIcon'],
    [Mini.ChatBubbleBottomCenterTextIcon,'ChatBubbleBottomCenterTextIcon'],
    [Mini.ChatBubbleLeftEllipsisIcon,'ChatBubbleLeftEllipsisIcon'],
    [Mini.ChatBubbleLeftIcon,'ChatBubbleLeftIcon'],
    [Mini.ChatBubbleLeftRightIcon,'ChatBubbleLeftRightIcon'],
    [Mini.ChatBubbleOvalLeftEllipsisIcon,'ChatBubbleOvalLeftEllipsisIcon'],
    [Mini.ChatBubbleOvalLeftIcon,'ChatBubbleOvalLeftIcon'],
    [Mini.CheckBadgeIcon,'CheckBadgeIcon'],
    [Mini.CheckCircleIcon,'CheckCircleIcon'],
    [Mini.CheckIcon,'CheckIcon'],
    [Mini.ChevronDoubleDownIcon,'ChevronDoubleDownIcon'],
    [Mini.ChevronDoubleLeftIcon,'ChevronDoubleLeftIcon'],
    [Mini.ChevronDoubleRightIcon,'ChevronDoubleRightIcon'],
    [Mini.ChevronDoubleUpIcon,'ChevronDoubleUpIcon'],
    [Mini.ChevronDownIcon,'ChevronDownIcon'],
    [Mini.ChevronLeftIcon,'ChevronLeftIcon'],
    [Mini.ChevronRightIcon,'ChevronRightIcon'],
    [Mini.ChevronUpDownIcon,'ChevronUpDownIcon'],
    [Mini.ChevronUpIcon,'ChevronUpIcon'],
    [Mini.CircleStackIcon,'CircleStackIcon'],
    [Mini.ClipboardDocumentCheckIcon,'ClipboardDocumentCheckIcon'],
    [Mini.ClipboardDocumentIcon,'ClipboardDocumentIcon'],
    [Mini.ClipboardDocumentListIcon,'ClipboardDocumentListIcon'],
    [Mini.ClipboardIcon,'ClipboardIcon'],
    [Mini.ClockIcon,'ClockIcon'],
    [Mini.CloudArrowDownIcon,'CloudArrowDownIcon'],
    [Mini.CloudArrowUpIcon,'CloudArrowUpIcon'],
    [Mini.CloudIcon,'CloudIcon'],
    [Mini.CodeBracketIcon,'CodeBracketIcon'],
    [Mini.CodeBracketSquareIcon,'CodeBracketSquareIcon'],
    [Mini.Cog6ToothIcon,'Cog6ToothIcon'],
    [Mini.Cog8ToothIcon,'Cog8ToothIcon'],
    [Mini.CogIcon,'CogIcon'],
    [Mini.CommandLineIcon,'CommandLineIcon'],
    [Mini.ComputerDesktopIcon,'ComputerDesktopIcon'],
    [Mini.CpuChipIcon,'CpuChipIcon'],
    [Mini.CreditCardIcon,'CreditCardIcon'],
    [Mini.CubeIcon,'CubeIcon'],
    [Mini.CubeTransparentIcon,'CubeTransparentIcon'],
    [Mini.CurrencyBangladeshiIcon,'CurrencyBangladeshiIcon'],
    [Mini.CurrencyDollarIcon,'CurrencyDollarIcon'],
    [Mini.CurrencyEuroIcon,'CurrencyEuroIcon'],
    [Mini.CurrencyPoundIcon,'CurrencyPoundIcon'],
    [Mini.CurrencyRupeeIcon,'CurrencyRupeeIcon'],
    [Mini.CurrencyYenIcon,'CurrencyYenIcon'],
    [Mini.CursorArrowRaysIcon,'CursorArrowRaysIcon'],
    [Mini.CursorArrowRippleIcon,'CursorArrowRippleIcon'],
    [Mini.DevicePhoneMobileIcon,'DevicePhoneMobileIcon'],
    [Mini.DeviceTabletIcon,'DeviceTabletIcon'],
    [Mini.DocumentArrowDownIcon,'DocumentArrowDownIcon'],
    [Mini.DocumentArrowUpIcon,'DocumentArrowUpIcon'],
    [Mini.DocumentChartBarIcon,'DocumentChartBarIcon'],
    [Mini.DocumentCheckIcon,'DocumentCheckIcon'],
    [Mini.DocumentDuplicateIcon,'DocumentDuplicateIcon'],
    [Mini.DocumentIcon,'DocumentIcon'],
    [Mini.DocumentMagnifyingGlassIcon,'DocumentMagnifyingGlassIcon'],
    [Mini.DocumentMinusIcon,'DocumentMinusIcon'],
    [Mini.DocumentPlusIcon,'DocumentPlusIcon'],
    [Mini.DocumentTextIcon,'DocumentTextIcon'],
    [Mini.EllipsisHorizontalCircleIcon,'EllipsisHorizontalCircleIcon'],
    [Mini.EllipsisHorizontalIcon,'EllipsisHorizontalIcon'],
    [Mini.EllipsisVerticalIcon,'EllipsisVerticalIcon'],
    [Mini.EnvelopeIcon,'EnvelopeIcon'],
    [Mini.EnvelopeOpenIcon,'EnvelopeOpenIcon'],
    [Mini.ExclamationCircleIcon,'ExclamationCircleIcon'],
    [Mini.ExclamationTriangleIcon,'ExclamationTriangleIcon'],
    [Mini.EyeIcon,'EyeIcon'],
    [Mini.EyeSlashIcon,'EyeSlashIcon'],
    [Mini.FaceFrownIcon,'FaceFrownIcon'],
    [Mini.FaceSmileIcon,'FaceSmileIcon'],
    [Mini.FilmIcon,'FilmIcon'],
    [Mini.FingerPrintIcon,'FingerPrintIcon'],
    [Mini.FireIcon,'FireIcon'],
    [Mini.FlagIcon,'FlagIcon'],
    [Mini.FolderArrowDownIcon,'FolderArrowDownIcon'],
    [Mini.FolderIcon,'FolderIcon'],
    [Mini.FolderMinusIcon,'FolderMinusIcon'],
    [Mini.FolderOpenIcon,'FolderOpenIcon'],
    [Mini.FolderPlusIcon,'FolderPlusIcon'],
    [Mini.ForwardIcon,'ForwardIcon'],
    [Mini.FunnelIcon,'FunnelIcon'],
    [Mini.GifIcon,'GifIcon'],
    [Mini.GiftIcon,'GiftIcon'],
    [Mini.GiftTopIcon,'GiftTopIcon'],
    [Mini.GlobeAltIcon,'GlobeAltIcon'],
    [Mini.GlobeAmericasIcon,'GlobeAmericasIcon'],
    [Mini.GlobeAsiaAustraliaIcon,'GlobeAsiaAustraliaIcon'],
    [Mini.GlobeEuropeAfricaIcon,'GlobeEuropeAfricaIcon'],
    [Mini.HandRaisedIcon,'HandRaisedIcon'],
    [Mini.HandThumbDownIcon,'HandThumbDownIcon'],
    [Mini.HandThumbUpIcon,'HandThumbUpIcon'],
    [Mini.HashtagIcon,'HashtagIcon'],
    [Mini.HeartIcon,'HeartIcon'],
    [Mini.HomeIcon,'HomeIcon'],
    [Mini.HomeModernIcon,'HomeModernIcon'],
    [Mini.IdentificationIcon,'IdentificationIcon'],
    [Mini.InboxArrowDownIcon,'InboxArrowDownIcon'],
    [Mini.InboxIcon,'InboxIcon'],
    [Mini.InboxStackIcon,'InboxStackIcon'],
    [Mini.InformationCircleIcon,'InformationCircleIcon'],
    [Mini.KeyIcon,'KeyIcon'],
    [Mini.LanguageIcon,'LanguageIcon'],
    [Mini.LifebuoyIcon,'LifebuoyIcon'],
    [Mini.LightBulbIcon,'LightBulbIcon'],
    [Mini.LinkIcon,'LinkIcon'],
    [Mini.ListBulletIcon,'ListBulletIcon'],
    [Mini.LockClosedIcon,'LockClosedIcon'],
    [Mini.LockOpenIcon,'LockOpenIcon'],
    [Mini.MagnifyingGlassCircleIcon,'MagnifyingGlassCircleIcon'],
    [Mini.MagnifyingGlassIcon,'MagnifyingGlassIcon'],
    [Mini.MagnifyingGlassMinusIcon,'MagnifyingGlassMinusIcon'],
    [Mini.MagnifyingGlassPlusIcon,'MagnifyingGlassPlusIcon'],
    [Mini.MapIcon,'MapIcon'],
    [Mini.MapPinIcon,'MapPinIcon'],
    [Mini.MegaphoneIcon,'MegaphoneIcon'],
    [Mini.MicrophoneIcon,'MicrophoneIcon'],
    [Mini.MinusCircleIcon,'MinusCircleIcon'],
    [Mini.MinusIcon,'MinusIcon'],
    [Mini.MinusSmallIcon,'MinusSmallIcon'],
    [Mini.MoonIcon,'MoonIcon'],
    [Mini.MusicalNoteIcon,'MusicalNoteIcon'],
    [Mini.NewspaperIcon,'NewspaperIcon'],
    [Mini.NoSymbolIcon,'NoSymbolIcon'],
    [Mini.PaintBrushIcon,'PaintBrushIcon'],
    [Mini.PaperAirplaneIcon,'PaperAirplaneIcon'],
    [Mini.PaperClipIcon,'PaperClipIcon'],
    [Mini.PauseIcon,'PauseIcon'],
    [Mini.PencilIcon,'PencilIcon'],
    [Mini.PencilSquareIcon,'PencilSquareIcon'],
    [Mini.PhoneArrowDownLeftIcon,'PhoneArrowDownLeftIcon'],
    [Mini.PhoneArrowUpRightIcon,'PhoneArrowUpRightIcon'],
    [Mini.PhoneIcon,'PhoneIcon'],
    [Mini.PhoneXMarkIcon,'PhoneXMarkIcon'],
    [Mini.PhotoIcon,'PhotoIcon'],
    [Mini.PlayIcon,'PlayIcon'],
    [Mini.PlayPauseIcon,'PlayPauseIcon'],
    [Mini.PlusCircleIcon,'PlusCircleIcon'],
    [Mini.PlusIcon,'PlusIcon'],
    [Mini.PlusSmallIcon,'PlusSmallIcon'],
    [Mini.PresentationChartBarIcon,'PresentationChartBarIcon'],
    [Mini.PresentationChartLineIcon,'PresentationChartLineIcon'],
    [Mini.PrinterIcon,'PrinterIcon'],
    [Mini.PuzzlePieceIcon,'PuzzlePieceIcon'],
    [Mini.QrCodeIcon,'QrCodeIcon'],
    [Mini.QuestionMarkCircleIcon,'QuestionMarkCircleIcon'],
    [Mini.QueueListIcon,'QueueListIcon'],
    [Mini.RadioIcon,'RadioIcon'],
    [Mini.ReceiptPercentIcon,'ReceiptPercentIcon'],
    [Mini.ReceiptRefundIcon,'ReceiptRefundIcon'],
    [Mini.RectangleGroupIcon,'RectangleGroupIcon'],
    [Mini.RectangleStackIcon,'RectangleStackIcon'],
    [Mini.RssIcon,'RssIcon'],
    [Mini.ScaleIcon,'ScaleIcon'],
    [Mini.ScissorsIcon,'ScissorsIcon'],
    [Mini.ServerIcon,'ServerIcon'],
    [Mini.ServerStackIcon,'ServerStackIcon'],
    [Mini.ShareIcon,'ShareIcon'],
    [Mini.ShieldCheckIcon,'ShieldCheckIcon'],
    [Mini.ShieldExclamationIcon,'ShieldExclamationIcon'],
    [Mini.ShoppingBagIcon,'ShoppingBagIcon'],
    [Mini.ShoppingCartIcon,'ShoppingCartIcon'],
    [Mini.SignalIcon,'SignalIcon'],
    [Mini.SignalSlashIcon,'SignalSlashIcon'],
    [Mini.SparklesIcon,'SparklesIcon'],
    [Mini.SpeakerWaveIcon,'SpeakerWaveIcon'],
    [Mini.SpeakerXMarkIcon,'SpeakerXMarkIcon'],
    [Mini.Square2StackIcon,'Square2StackIcon'],
    [Mini.Squares2X2Icon,'Squares2X2Icon'],
    [Mini.SquaresPlusIcon,'SquaresPlusIcon'],
    [Mini.StarIcon,'StarIcon'],
    [Mini.StopIcon,'StopIcon'],
    [Mini.SunIcon,'SunIcon'],
    [Mini.SwatchIcon,'SwatchIcon'],
    [Mini.TableCellsIcon,'TableCellsIcon'],
    [Mini.TagIcon,'TagIcon'],
    [Mini.TicketIcon,'TicketIcon'],
    [Mini.TrashIcon,'TrashIcon'],
    [Mini.TruckIcon,'TruckIcon'],
    [Mini.UserCircleIcon,'UserCircleIcon'],
    [Mini.UserGroupIcon,'UserGroupIcon'],
    [Mini.UserIcon,'UserIcon'],
    [Mini.UserMinusIcon,'UserMinusIcon'],
    [Mini.UserPlusIcon,'UserPlusIcon'],
    [Mini.UsersIcon,'UsersIcon'],
    [Mini.VariableIcon,'VariableIcon'],
    [Mini.VideoCameraIcon,'VideoCameraIcon'],
    [Mini.VideoCameraSlashIcon,'VideoCameraSlashIcon'],
    [Mini.ViewColumnsIcon,'ViewColumnsIcon'],
    [Mini.WalletIcon,'WalletIcon'],
    [Mini.WifiIcon,'WifiIcon'],
    [Mini.WrenchIcon,'WrenchIcon'],
    [Mini.WrenchScrewdriverIcon,'WrenchScrewdriverIcon'],
    [Mini.XCircleIcon,'XCircleIcon'],
    [Mini.XMarkIcon,'XMarkIcon'],
] as [React.FunctionComponent<React.ComponentProps<'svg'>>, string][]


export const AllIconsBase = ({ list = solidList, textColor = 'text-gray-400', iconClass = 'h-6' }) => {
  return (
  <div className='flex flex-wrap justify-center gap-4 text-center'>
    {list.map(Icon => <IconSample Icon={Icon[0]} name={Icon[1]} textColor={textColor} iconClass={iconClass} />)}
  </div>
  )
}

export const AllIcons = ({textColor = 'text-gray-400', iconClass = 'h-6' }) =>
  <AllIconsBase list={prismList} textColor={textColor} iconClass={iconClass} />
export const AllIconsSolid = ({textColor = 'text-gray-400', iconClass = 'h-6' }) =>
  <AllIconsBase list={solidList} textColor={textColor} iconClass={iconClass} />

  export const AllIconsMini = ({textColor = 'text-gray-400', iconClass = 'h-6' }) =>
  <AllIconsBase list={miniList} textColor={textColor} iconClass={iconClass} />

export const AllIconsOutline = ({textColor = 'text-gray-400', iconClass = 'h-6' }) =>
  <AllIconsBase list={outlineList} textColor={textColor} iconClass={iconClass} />

  export const AllInterstateIcons = ({textColor = 'text-gray-400', iconClass = 'h-6' }) =>
  <AllIconsBase list={interstateList} textColor={textColor} iconClass={iconClass} />
