/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IdsCard {
        /**
          * (optional) the title text of the card. if using this, do not use the `card-title` slot
         */
        "header": string;
        /**
          * (optional) denotes if the component is to be displayed horizontally
         */
        "horizontal": boolean;
        /**
          * (optional) the media source of the card. if using this, do not use the `card-media` slot
         */
        "media": string;
    }
}
declare global {
    interface HTMLIdsCardElement extends Components.IdsCard, HTMLStencilElement {
    }
    var HTMLIdsCardElement: {
        prototype: HTMLIdsCardElement;
        new (): HTMLIdsCardElement;
    };
    interface HTMLElementTagNameMap {
        "ids-card": HTMLIdsCardElement;
    }
}
declare namespace LocalJSX {
    interface IdsCard {
        /**
          * (optional) the title text of the card. if using this, do not use the `card-title` slot
         */
        "header"?: string;
        /**
          * (optional) denotes if the component is to be displayed horizontally
         */
        "horizontal"?: boolean;
        /**
          * (optional) the media source of the card. if using this, do not use the `card-media` slot
         */
        "media"?: string;
    }
    interface IntrinsicElements {
        "ids-card": IdsCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ids-card": LocalJSX.IdsCard & JSXBase.HTMLAttributes<HTMLIdsCardElement>;
        }
    }
}
