// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    { type: 'autogenerated', dirName: 'getting-started' },
  ],
  foundationSidebar: [
    { type: 'autogenerated', dirName: 'foundation' },
  ],
  stylesSidebar: [
    { type: 'autogenerated', dirName: 'styles' },
  ],
  tokensSidebar: [
    { type: 'autogenerated', dirName: 'tokens' },
  ],
  designPattersSidebar: [
    { type: 'autogenerated', dirName: 'design-patterns' },
  ],
  componentsSidebar: [
    { type: 'autogenerated', dirName: 'components' }
  ],
};

module.exports = sidebars;
