// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  componentsSidebar: [
    { type: 'autogenerated', dirName: 'components' }
  ],
};

module.exports = sidebars;
