name: Deployer

on:
  push:
    branches:
      - next
      - feature/*

jobs:
  build:
      name: Build and Deploy Storybook
      timeout-minutes: 15
      runs-on:  [self-hosted, Linux, CAI-Enterprise]
      environment:
        name: development
        url: https://pages.ghe.coxautoinc.com/prism/prism2/
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      env:
        GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
        # GH_USERNAME: man.TeamPrism
        # GH_EMAIL: man.TeamPrism@coxautoinc.com
        # TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      strategy:
        matrix:
          node-version: [16.x]
      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16

        - name: Install pnpm
          run: npm install -g pnpm

        - name: Install dependencies
          run: pnpm install

        - name: Deploy Storybook
          run: |
            git remote set-url origin https://git:${GITHUB_TOKEN}@ghe.coxautoinc.com/${GITHUB_REPOSITORY}.git
            export NODE_OPTIONS="--max_old_space_size=4096"
            BASE=/prism/prism2 pnpm run deploy
          env:
            GH_USERNAME: man.TeamPrism
            GH_EMAIL: man.TeamPrism@coxautoinc.com
            GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
            

