name: Smoketest

on:
  push:
    branches: ["main","next"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
      name: Build and Test Packages
      timeout-minutes: 15
      runs-on:  [self-hosted, Linux, CAI-Enterprise]
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      # env:
        # TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        # TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      strategy:
        matrix:
          node-version: [16.x]
      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16

        - name: Install pnpm
          run: npm install -g pnpm

        - name: Install dependencies
          run: pnpm install

        - name: Build Storybook
          run: pnpm run build-storybook

        - name: Build
          run: pnpm run build

        - name: Test
          run: pnpm run test

